[pytest]
testpaths = tests
pythonpath = .
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function

addopts =
    --cov=app
    --cov-report=term-missing:skip-covered
    --cov-fail-under=52
